apiVersion: apps/v1

kind: Deployment

metadata:
  name: ms-event-bus-depl

spec:
  replicas: 1

  selector:
    matchLabels:
      app: event-bus

  template:
    metadata:
      labels:
        app: event-bus

    spec:
      containers:
      - name: event-bus
        image: microservices-event-bus
        imagePullPolicy: Never
        ports:
        - containerPort: 4005

---

apiVersion: v1

kind: Service

metadata:
  name: ms-event-bus-srv

spec:
  selector:
    app: event-bus

  ports:
    - protocol: TCP
      port: 4005
      targetPort: 4005

  type: ClusterIP