apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  
  - http:
      paths:
      - path: /posts/create
        pathType: ImplementationSpecific
        backend:
          service:
            name: ms-posts-srv
            port:
              number: 4000
      - path: /posts
        pathType: ImplementationSpecific
        backend:
          service:
            name: ms-query-srv
            port:
              number: 4002
      - path: /posts/(.*)/comments
        pathType: ImplementationSpecific
        backend:
          service:
            name: ms-comments-srv
            port:
              number: 4001
      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: ms-client-srv
            port:
              number: 3000