apiVersion: apps/v1

kind: Deployment

metadata:
  name: ms_posts-dpl

spec:
  replicas: 1

  selector:
    matchLabels:
      app: posts

  template:

    metadata:
      labels:
        app: posts

    spec:
      containers:
        - name: posts-container
          image: ms_posts
          ports:
            - containerPort: 4000
