apiVersion: apps/v1

kind: Deployment

metadata:
  name: ms-query-dpl

spec:
  replicas: 1

  selector:
    matchLabels:
      app: query

  template:
    metadata:
      labels:
        app: query

    spec:
      containers:
        - name: query-container
          image: ms-query
          ports:
            - containerPort: 4002

---

apiVersion: v1

kind: Service

metadata:
  name: ms-query-srv

spec:
  selector:
    app: query

  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002

  type: ClusterIP